image:
  repository: plutocholia/ipruler-operator
  tag: ~
  pullPolicy: IfNotPresent

config:
  agent-api-port: 9301
  node-cleanup-on-deletion: true

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

replicas: 1

ipruler-agent:
  enabled: true

crds:
  enabled: true