---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ipruler-pegah-tech-v1-clusterconfig
  failurePolicy: Fail
  name: vclusterconfig.kb.io
  rules:
  - apiGroups:
    - ipruler.pegah.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterconfigs
  sideEffects: None
