# permissions for end users to view fullconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ipruler-operator
    app.kubernetes.io/managed-by: kustomize
  name: fullconfig-viewer-role
rules:
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - fullconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - fullconfigs/status
  verbs:
  - get
