# permissions for end users to edit nodeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ipruler-controller
    app.kubernetes.io/managed-by: kustomize
  name: nodeconfig-editor-role
rules:
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - nodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - nodeconfigs/status
  verbs:
  - get
