---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - clusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - clusterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - clusterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - fullconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - fullconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - fullconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - nodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - nodeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ipruler.pegah.tech
  resources:
  - nodeconfigs/status
  verbs:
  - get
  - patch
  - update
