apiVersion: ipruler.pegah.tech/v1
kind: NodeConfig
metadata:
  labels:
    app.kubernetes.io/name: ipruler-controller
    app.kubernetes.io/managed-by: kustomize
  name: nodeconfig-sample
spec:
  # TODO(user): Add fields here
