apiVersion: ipruler.pegah.tech/v1
kind: NodeConfig
metadata:
  labels:
    app.kubernetes.io/name: ipruler-controller
    app.kubernetes.io/managed-by: kustomize
  name: nodeconfig-sample
spec:
  nodeSelector:
    networking.type: "eth2"
  config:
    rules:
    - from: 172.31.201.13/32
      table: 102
    - from: 172.31.201.14/32
      table: 102